### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by JEDIBC** [FriendsOfPHP/pickleweb#17]
What are the coding standards used for the project ? 

My IDE (phpstorm) is configured with Symfony2 CS but I see @pierrejoye fixing the spaces between . on string concatenation :stuck_out_tongue: 

As I've the habit of regularly launch the auto-format of the code, it would be usefull to know which CS is used and perhaps enforce verification via a tool like https://github.com/M6Web/Coke on build process on Travis CI.

**Comment by pierrejoye** [comment]
Old habit :)

I will try to pay more attention :D

I however run php-cs regularly!

**Comment by pierrejoye** [comment]
and php-cs-fixes says:
- operators_spaces                   [symfony]
                                     Operators should be arounded by at
                                     least one space.

not sure anymore. Up to you, if you have a config file, we can use it :)

**Comment by JEDIBC** [comment]
I use https://github.com/M6Web/Symfony2-coding-standard as config file to use with coke.
I can share my phpstorm conf if anyone is interested. I'll add the dependancies in composer.json at noon and fix the CS.

**Comment by JEDIBC** [comment]
Done in a3f5f7122b0750363090188ea9b2cb7bb56cfd26

**Comment by pierrejoye** [comment]
Do you have the file for php-cs? Or is it the same?

**Comment by JEDIBC** [comment]
Coke is a wrapper around php-cs so the m6web coding standards will work with it

**Comment by pierrejoye** [comment]
Great, so I can use this file for php-cs, maybe add it to /doc?

**Comment by JEDIBC** [comment]
No need, it is handled by composer

**Comment by pierrejoye** [comment]
I run php-cs before every commit, that's why

**Comment by JEDIBC** [comment]
so run vendor/bin/coke now ;)

**Comment by pierrejoye** [comment]
Wooot! You rock!
