### ISSUE TITLE
add CS bin command

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickleweb#19]
Now that we have coke, it would be nice to add the respective commands to bin/ to fix CS or detect errors.

I can then use them as git prehook and stop on error

**Comment by JEDIBC** [comment]
You already can use coke as git prehook. See http://tech.m6web.fr/coke-pour-bien-sniffer-son-code/
For automatic fix coke depends on phpCS ~1.5 and fixing is on 2.3. I tried tu manually add 2.3 dependancy on composer.json which result in a `Your requirements could not be resolved to an installable set of packages.` :disappointed:

**Comment by pierrejoye** [comment]
I am talking about https://github.com/FriendsOfPHP/PHP-CS-Fixer

Or what do you use?

I would rather prefer small but out of the box working tools instead of something that cannot be used easily :)

**Comment by JEDIBC** [comment]
You can add the dependancy in the require-dev section of composer.json if you want.
I don't use a command line tools to fix CS. My IDE do it and the one he can't fix I do it manually.

**Comment by pierrejoye** [comment]
but what is the point of coke then?

**Comment by JEDIBC** [comment]
Only checking coding standard with https://github.com/squizlabs/PHP_CodeSniffer according to a specified standard. I thought that was the CS tool you were using.

**Comment by pierrejoye** [comment]
Ah! :)

Any chance to rely on php-cs-fixer then? Could be possible to add the rules
you like :)

**Comment by JEDIBC** [comment]
I'll make some tests but my priority for now is user persistency in redis.

**Comment by pierrejoye** [comment]
everything in there now, thanks!

use vendor/bin/php-cs-fixer :)
