### ISSUE TITLE
Error in Docker PHP

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickleweb#21]
Keep getting this error. Are we relying on the right images?

E: Failed to fetch http://http.debian.net/debian/pool/main/e/expat/libexpat1_2.1.0-6+b3_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]

E: Failed to fetch http://http.debian.net/debian/pool/main/l/less/less_458-3_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by JEDIBC** [comment]
Just rebuild all and don't have the problem

**Comment by JEDIBC** [comment]
Do you still have the problem @pierrejoye  ?

**Comment by pierrejoye** [comment]
Yes,  I will update to docker 1.6 and check again. If it fails, updating
tonjessie next week will surely make it :)

**Comment by JEDIBC** [comment]
I just tried on macOSX and got :
`Cannot start container a1efa1281c5a805ec70798d36a70cf5f484d7aab2eec64735e949d38fec0c73a: Cannot link to a non running container: /pickleweb_redis_1 AS /pickleweb_web_1/pickleweb_redis_1`

**Comment by JEDIBC** [comment]
Seems to be a write authorisation problem on data/redis

**Comment by jubianchi** [comment]
@JEDIBC I also have trouble on OSX with b2d : permissions on volumes shared with containers using custome users are wrong.

What I usually do is a good-old `chmod -R 777 data/redis` on host machine and it fixes the problem.

**Comment by JEDIBC** [comment]
Unfortunately it isn't. It will fix the problem once you start the container for the first time but the next time it'll be unable to read form the file generated.

**Comment by pierrejoye** [comment]
The initial bug is actually not a bug. It needs docker 1.6 and latest/recent docker-compose.

I also update the sample config.json to match the redis host name (redis, it uses the name of the container)
