### ISSUE TITLE
User instance not persistent or readonly

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickleweb#24]
Using:
https://github.com/FriendsOfPHP/pickleweb/blob/master/src/Controller/PackageController.php#L63

Forced to use local variable $user, modify the entity and store it (UserRepository).

Using $this->app->user, no modification are taken into account.

I did not look into the code to figure out why but not very critical for now, would be nice to be able to alter User meta and store them back to redis using the app::user

**Comment by pierrejoye** [comment]
Seems to be a global issue. Profile and co does not show up with what is stored in redis storage nor the json static is updated.

Maybe we should just drop json for users data, ensure that any update actually update the user storage as well. While I like the idea of having the public user data statically available as json.

thoughts?

**Comment by JEDIBC** [comment]
As said on irc, having an always fresh user from redis on $this->app->user() is easy but automatically persisting is a no go for me. Way to complicated to know when persisting, how many times, etc...
A manual persist should be done, has it is done in all ORMs.
