### ISSUE TITLE
implement search

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickleweb#30]
Implement search using elasticsearch

See https://github.com/FriendsOfPHP/pickle/issues/108  and https://github.com/FriendsOfPHP/pickleweb/issues/27 as well

**Comment by JEDIBC** [comment]
We need a list of what keyword we can search from

**Comment by pierrejoye** [comment]
Created by the devs while registering sound the best way, or?

Maybe grab the tags from pecl or packagist to start with.

We can always reduce, increase or optimize the list.

**Comment by pierrejoye** [comment]
ah:

https://packagist.org/about

Let the developers do it straight in composer.json and aggregate them on import :)

**Comment by pierrejoye** [comment]
keywords are now stored in the extensions, if present

**Comment by pierrejoye** [comment]
Basic search implemented, json and html results.

We can open a new issue if we want more fancy search features.
