### ISSUE TITLE
Provide list of bundled extensions per PHP branch

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickleweb#36]
A simple list of the extensions bundled in the core per major version.

pickle cmd line or composer can then fetch them to directly deal correctly with it and tell the user to either enable, install or rebuild them php, alternatively rebuild php.

The list will be:

[
'extname' => false,
'extname' => 'vendor/repo',
]

false means this extension is only maintained in core.
'vendor/repo' is the name of the extensions within pickle, so if an newer external release is available, it can be installed.

Files:
/json/php-core-5.4.json
/json/php-core-5.5.json
/json/php-core-5.6.json
/json/php-core-7.0.json

**Comment by weltling** [comment]
This would probably need the PHP version relation as well, at least for some cases. As extensions come and go.

**Comment by pierrejoye** [comment]
What the title said, it will be json per branch :)

**Comment by weltling** [comment]
Got it :) .. this is probably also easier also for, extending later, when HHVM or something else comes in addition.

**Comment by pierrejoye** [comment]
https://github.com/FriendsOfPHP/pickleweb/commit/80eb8a15b5e5c2cf1865472298d03e383654d2ee

WiP
