### ISSUE TITLE
Difference in the github hook configuration impeds data delivery

### ISSUE THREAD

**Issue by weltling** [FriendsOfPHP/pickleweb#37]
While testing the pickleweb site, I've discovered, that it's not prepared for all the variants of the data delivery from github. Thus, under the option
- Which events would you like to trigger this webhook?

when any of the options 
- Just the push event. 
- Send me everything. 

is used, the payload json format is different. In this case pickleweb fails to parse it so no data update happens to the particular item. The only way i could bring the github data to be accepted right now is using the
- Let me select individual events.

option and manually enabling the create event (in addition to the preselected push event). Here are the both different JSON format variants

https://gist.github.com/weltling/f97b1cc4630c071829f3
https://gist.github.com/weltling/13a075879eb91e922d61

Also note that if the create event is enabled manually, then after the tag creation the headers contain
- X-GitHub-Event: create

otherwise it contains
- X-GitHub-Event: push

**Comment by pierrejoye** [comment]
For the hooks, we need only the tab creation/deletion and release.

For now. :)

I forgot to add that to the wiki.

**Comment by weltling** [comment]
When looking at https://developer.github.com/v3/activity/events/types/ and also analyzing the code, it appears that pickleweb doesn't check the exact X-GitHub-Event types. I guess our API should handle the enevt types to reliably parse the formats. Supporting this looks however like a big refactoring need, also taking in account #38.

Yep, for now it were enough to add to the documentation, that manually selecting the required events (and calling the exact events we support) is the recommended way. However choosing something like "send only pushes" or "send all" would be much more user friendly. First guess is also that all the requiered data is actually delivered and only needs to be parsed accordingly to the event type.

**Comment by pierrejoye** [comment]
Because it expects only tag or release.

That's fine for now.

Once we need more we can use the github controller to do the payload check
and use the right model then.

But for now let keep it this way, add the correct events to the wiki and
stick to it.

Let get the beast out.

**Comment by pborreli** [comment]
> Also note that if the create event is enabled manually, then after the tag creation the headers contain
> X-GitHub-Event: create
> otherwise it contains
> X-GitHub-Event: create

Do you mean that ?

**Comment by weltling** [comment]
@pborreli c/p issue :)

`X-GitHub-Event: push` vs `X-GitHub-Event: create`

**Comment by pborreli** [comment]
ha it makes more sense, I edited your first issue, correct if it's not the good order please

**Comment by weltling** [comment]
@pborelli, yep, that was vice versa actually. Thanks for keeping the eyes on it.

**Comment by weltling** [comment]
Oki, wiki updated.

**Comment by pierrejoye** [comment]
And?

Does it work when correctly configured?

It is critical to focus on getting the beast out. Simple bailout with a
message will be enough.

**Comment by weltling** [comment]
Yeah, when the create event is selected manually, it works. Here's my current host http://9fe756ee.ngrok.io/package/weltling/igbinary

I'm testing the release and delete events right now.

**Comment by pierrejoye** [comment]
No need it is not implemented.

I just keep it as we will support release soon. See the code in the github
controller, it bail out on release.

**Comment by weltling** [comment]
ahh, ok ... good, then contining further testing in the other areas :)

**Comment by pborreli** [comment]
thanks @weltling :bouquet:

**Comment by weltling** [comment]
Another case for this kind of issue - `X-GitHub-Event: ping` . This header and the corresponding payload are sent when the hook is being registered for the first time (at least, dunno whether it has more usages). This probably doesn't imped the main function, still one more case we should care about the event types.

**Comment by pierrejoye** [comment]
checks have been implemented, only ping/create/delete are supported.

Any other op will result in a (well formed) response saying invalid op.
