### ISSUE TITLE
Vendors handling while supporting different dev platforms (github, bitbucket, etc.)

### ISSUE THREAD

**Issue by weltling** [FriendsOfPHP/pickleweb#41]
I might err, but currently we've also an issue with the vendors coming from different locations. Example situation
- vendor0 is on github
- vendor0 is on bitbucket

Those two are different people. Each of them has the same `vendor0/extname`. Here we currently run into the situation first with json handling in pickleweb as it's not separated by the vendor location. Say it would save to the same `web/json/vendor0` for both vendors.

There's no issue created for pickle yet, but it also doesn't really handle the communication with pickleweb yet. So it would need to match with pickleweb anyway when implemented. In this regard also rmtools is affected, as it'll need to handle the vendors from different locations for uploading the windows builds.

The other sub case of this which needs to be handled is when the name in composer.json doesn't have a vendor. While it can be probably fixed for pickle convert, pickleweb might receive some hand made composer.json.

**Comment by pierrejoye** [comment]
Some notes:

For the implementation:
name referst to the full name "vendor/packageName"

vendor refers to the 1st part of the name
packageName referst to the 2nd of the name

on import:
- master must have valid composer.json
- vendor/pkgname taken from composer.json only
- for any tag without composer.json, the vendor/name is taken from master's composer.json (for example old releases with package.xml or nothing)
- if any composer.json is present in a tag, name must match with the master's one if it does not match, this tag is ignored

**Comment by pierrejoye** [comment]
Should be fixed

@weltling can you check pls?

**Comment by pierrejoye** [comment]
@weltling ping?

**Comment by weltling** [comment]
Looks fine so far i've tested, also regarding #42.
