### ISSUE TITLE
Exception when registering a new package

### ISSUE THREAD

**Issue by weltling** [FriendsOfPHP/pickleweb#42]
Slim Application Error

The application could not run because of the following error:
Details
Type: ErrorException
Code: 8
Message: Undefined index: time
File: E:\repo_pickle\pickleweb\src\Entity\Extension.php
Line: 108
Trace
#0 E:\repo_pickle\pickleweb\src\Entity\Extension.php(108): Slim\Slim::handleErrors(8, 'Undefined index...', 'E:\repo_pickle\...', 108, Array)
#1 E:\repo_pickle\pickleweb\src\Controller\PackageController.php(233): PickleWeb\Entity\Extension->setFromRepository(Object(PickleWeb\Repository\Github), Object(Composer\IO\BufferIO))
#2 [internal function]: PickleWeb\Controller\PackageController->registerPackageAction()
#3 E:\repo_pickle\pickleweb\vendor\akrabat\rka-slim-controller\RKA\Slim.php(79): call_user_func_array(Array, Array)
#4 [internal function]: RKA\Slim->RKA{closure}()
#5 E:\repo_pickle\pickleweb\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#6 E:\repo_pickle\pickleweb\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#7 E:\repo_pickle\pickleweb\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#8 E:\repo_pickle\pickleweb\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 E:\repo_pickle\pickleweb\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#10 E:\repo_pickle\pickleweb\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#11 E:\repo_pickle\pickleweb\src\Application.php(181): Slim\Slim->run()
#12 E:\repo_pickle\pickleweb\web\index.php(209): PickleWeb\Application->run()
#13 {main}

**Comment by weltling** [comment]
Seems the time array key isn't set somewhere, checking.

**Comment by pierrejoye** [comment]
Index.php, typo cachedr vs cachedir :)

**Comment by weltling** [comment]
ah, maybe that ... but i had actually eliminated that before. Also cleared the cache. Maybe something is missing in my composer.json and causes that.

**Comment by weltling** [comment]
I've more now, 

the `$information` delivered at src\Entity\Extension.php:95 is `bool(false)`

here's the tag

<pre>array(4) {
  ["version"]=>
  string(7) "1.5.2.0"
  ["tag"]=>
  string(5) "1.5.2"
  ["id"]=>
  string(40) "498fb25359c801e785bb899b18b4323ccbf425c5"
  ["source"]=>
  array(3) {
    ["type"]=>
    string(3) "git"
    ["url"]=>
    string(40) "https://github.com/weltling/igbinary.git"
    ["reference"]=>
    string(40) "498fb25359c801e785bb899b18b4323ccbf425c5"
  }
}</pre>

This is why the time is not set. Should the tag be abandoned in this case? I currently don't see it delivers the tag date with the payload.

**Comment by pierrejoye** [comment]
Hm, the time is always there. Not sure why, was it on import or on push?

**Comment by weltling** [comment]
It was a new package registration, brand empty database ... Looks like the time is always there when $information is correct, but it delivered false. That's why it's not set on src\Entity\Extension.php:108 where it wants to do `$information['time'] = $this->convertTime($information['time'])`.

**Comment by pierrejoye** [comment]
Question is why the time (pushed at) is not set :/

**Comment by weltling** [comment]
I've got one explanation - namely src\Repository\Github.php:getComposerInformation can return false only in one case - when the names of the extension don't match. Igbinary is what i've forked from you, now when i l debug this, in the tag https://github.com/weltling/igbinary/tree/1.5.2 the name is pierrejoye/igbinary in composer.json but weltling/igbinary in master. That way $information lands as false in src\Entity\Extension.php:108, so no time key is set.

**Comment by weltling** [comment]
it was actulaly testing #41, but was not obvious. However probably this tag should be ignored, what you meant there: "if any composer.json is present in a tag, name must match with the master's one if it does not match, this tag is ignored"

**Comment by weltling** [comment]
Fixed with 10a309892c55e4f60710a79a15a42f960d73c2b8
