### ISSUE TITLE
github/bitbucket oauth

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickleweb#6]
Little hack has been added, see https://github.com/FriendsOfPHP/pickleweb/blob/master/src/Action/AuthGithub.php

Ideas are:
- use only github or bitbucket for auth
- grab the profile
  . store it locally under /web/json/users/<github|other>/<login>.json

As of now only github is done, so some data normalization is required.

I kept it like that for now as I like to focus mainly on the hooks, to grab release infos, register package, etc. The way it is stored is open as well, it works just fine for now, and easy to cache.

Feel free to totally rewamp that part or even use another OAuth component.

**Comment by pierrejoye** [comment]
little update:
Moved OAuth to https://github.com/thephpleague/oauth2-client/

Did a bit of cleanup.

this module needs bitbucket support, but it works for now.

**Comment by pierrejoye** [comment]
Github is now in place, bitbucket support to be added to the league's oauth package

**Comment by Hywan** [comment]
Any PR? Please, track the commit :-).

**Comment by pierrejoye** [comment]
Well...yes I should :)
 We can start now but it is so small right now, many different commits, etc

**Comment by pierrejoye** [comment]
This is where it ends up now. Driver based so as soon as the league's oauth supports bitbucket, it will just work.

Keeping in mind the user details may need change once they are done with this part too.

**Comment by pierrejoye** [comment]
https://github.com/FriendsOfPHP/pickleweb/blob/master/src/Action/AuthAction.php

**Comment by pierrejoye** [comment]
https://github.com/Lusitanian/PHPoAuthLib for the example code for bitbucket

**Comment by JEDIBC** [comment]
I'll get inspiration in https://github.com/hwi/HWIOAuthBundle to refactor the authentication and add google & bitbucker oauth. In the meantime, there's a reflexion on how and where storing user info.

As we discussed with @pierrejoye , elasticsearch would probably be the main data storage so I suppose for users too. Now github, google & bitbucket don't provides the sames intel on users. I propose these base fields for a User :

. email <-- unique identifier of a user
. nickname
. realname
. profilepicture
. githubId
. googleId
. bitbucketId

This will have the same user be able to signin with multiple oauth provider.

To guaranty the uniqueness of the user on the data store, we'll have to use force the _id on the elasticsearch document. If it is too a pain to use it, I propose to store users and related data in redis.

**Comment by pierrejoye** [comment]
I like the meta part.

I am really not keen on _id for ES. Can we just use one handle as main id? it is needed to identify maintainers for a given extension, within the site.

**Comment by JEDIBC** [comment]
I've begun refactoring the oAuth part in 5ddfbc64f3698cfac4bbdb61917fc26f2f3f58f5

. the user Entity is here
. still need to code the user persister. I really think going to redis for that at first. Way quicker to code
. the providers must implements the same interface. Mandatory if we want to mix oauth1 and oauth2 authentication

**Comment by pierrejoye** [comment]
Go ahead with redis :)

Add a docker maybe.

**Comment by JEDIBC** [comment]
Of course I'll add a docker ;)

**Comment by JEDIBC** [comment]
Just added a config file in abbfebeef82cca8b2058c37778ded2c9dcdf1206 to avoid using export for handling oauth credentials.

**Comment by JEDIBC** [comment]
User persistence & deletion done in d98738f195ae82e195de5e9d3f8e6beea9c8b96c

**Comment by JEDIBC** [comment]
Added google oauth2 authentication in 7c21701edf330fe0899192a6f1f0b7f105d83e63

**Comment by JEDIBC** [comment]
21467232163b1e8d5012217d58ef97a440d37913 : Added bitbucket authentication & refactoring so store oauths states in redis instead of session

**Comment by JEDIBC** [comment]
The 3 oAuth providers are done so I close the issue.
